"""Pydantic schemas (request/response models) exposed through the API."""

from datetime import date, datetime
from enum import Enum

from pydantic import BaseModel, ConfigDict, Field


# --------------------------------------------------------------------------------------
# Shared / generic
# --------------------------------------------------------------------------------------


class ErrorResponse(BaseModel):
    """Consistent error body returned by every non-2xx response raised by this API."""

    detail: str = Field(..., description="Human-readable explanation of what went wrong.")


class HealthResponse(BaseModel):
    status: str = Field(..., examples=["ok"])


# --------------------------------------------------------------------------------------
# Customers
# --------------------------------------------------------------------------------------


class CustomerOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: int
    name: str
    email: str
    country: str
    signup_date: date


class CustomerListResponse(BaseModel):
    """Paginated list of customers."""

    items: list[CustomerOut]
    page: int = Field(..., description="Current page number (1-indexed).")
    page_size: int = Field(..., description="Number of items requested per page.")
    total: int = Field(..., description="Total number of customers matching the filter.")
    total_pages: int = Field(..., description="Total number of pages available.")


class CustomerSummary(BaseModel):
    """Aggregated order history for a single customer."""

    customer_id: int
    name: str
    email: str
    order_count: int = Field(..., description="Total number of orders placed (any status).")
    total_spend: float = Field(
        ..., description="Sum of quantity * unit_price across all non-cancelled orders."
    )
    first_order_date: datetime | None = Field(
        None, description="Timestamp of the customer's earliest order, if any."
    )
    last_order_date: datetime | None = Field(
        None, description="Timestamp of the customer's most recent order, if any."
    )


# --------------------------------------------------------------------------------------
# Metrics
# --------------------------------------------------------------------------------------


class RevenueGroupBy(str, Enum):
    DAY = "day"
    MONTH = "month"


class RevenueBucket(BaseModel):
    """Total revenue for a single time bucket (a day or a month, depending on `group_by`)."""

    period: str = Field(..., description="Bucket label, e.g. '2024-03-17' (day) or '2024-03' (month).")
    revenue: float = Field(..., description="Sum of quantity * unit_price for orders in this bucket.")
    order_count: int = Field(..., description="Number of distinct orders contributing to this bucket.")


class RevenueResponse(BaseModel):
    group_by: RevenueGroupBy
    start_date: date | None
    end_date: date | None
    total_revenue: float
    buckets: list[RevenueBucket]
    cached: bool = Field(
        ..., description="True if this response was served from the in-process cache."
    )


class TopProduct(BaseModel):
    product_id: int
    name: str
    category: str
    revenue: float = Field(..., description="Total revenue generated by this product.")
    units_sold: int = Field(..., description="Total quantity sold.")


class TopProductsResponse(BaseModel):
    start_date: date | None
    end_date: date | None
    limit: int
    products: list[TopProduct]
